### ISSUE TITLE
ParadeDB Logs Show Connection Error Despite Functional Database and Existing User/Database

### ISSUE THREAD

**Issue by Mohammed-Alhuraibi** [paradedb/charts#43] opened 2024-10-03 09:31 UTC
**Bug Description**

After setting up ParadeDB using the provided Helm chart and instructions, the database is functional and can be connected to without issues. However, the ParadeDB logs consistently show a connection error message, which may be causing the pod to be marked as unhealthy.
The error message in the logs is as follows:

```bash
{"msg":"DB not available, will retry","logging_pod":"paradedb-1","err":"failed to connect to `user=postgres database=postgres`: /controller/run/.s.PGSQL.5432 (/controller/run): dial error: dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory"}
```
This error persists even after customizing the `values.yaml` file for ParadeDB.

Importantly, both the `postgres` user and the `postgres` database exist, which makes this error message particularly puzzling.

**How To Reproduce**

1. Install the CloudNativePG Operator using the provided Helm commands.

```bash
helm repo add cnpg https://cloudnative-pg.github.io/charts
helm upgrade --install cnpg \
--namespace cnpg-system \
--create-namespace \
cnpg/cloudnative-pg
```

2. Deploy ParadeDB using the Helm commands provided in the README.

```bash
helm repo add paradedb https://paradedb.github.io/charts
helm upgrade --install paradedb \
--namespace paradedb-database \
--create-namespace \
paradedb/paradedb
```

3. Use port forwarding to expose the `paradedb-rw` service: 

```bash
kubectl port-forward svc/paradedb-rw 5432:5432 -n paradedb-database
```

4. Get the password for the postgres user:

```bash
kubectl get secret paradedb-superuser -n paradedb-database -o jsonpath='{.data.password}' | base64 --decode
```

5. Verify that the postgres user and postgres database exist by connecting to the database using your preferred database client. In my case, I used DBeaver-CE.

6. Check the logs of the ParadeDB pod:

```bash
kubectl logs paradedb-1 -n paradedb-database | grep "failed to connect"
```

**Proposed Fix**
I don't have a solution or a proposal for a fix at this time.

**Comment by itay-grudev** [comment] 2024-10-04 20:52
I reproduced the steps you described and I indeed saw the error, but for me this only occurred once during the cluster initialization. And that's ok if it only happens in the first several seconds when the cluster is booting up.

Are you encountering it after that as well?

**Comment by Mohammed-Alhuraibi** [comment] 2024-10-05 15:41
No, I'm not encountering it after the initial bootup. I think because of that error, my ArgoCD remains in out-of-sync mode, even though the application is working fine.

**Comment by philippemnoel** [comment] 2024-10-07 23:32
> No, I'm not encountering it after the initial bootup. I think because of that error, my ArgoCD remains in out-of-sync mode, even though the application is working fine.

Have you tried the official CloudNativePG helm chart? https://github.com/cloudnative-pg/charts Can you reproduce the issue there, or is it truly specific to ParadeDB?

**Comment by philippemnoel** [comment] 2024-10-07 23:35
@itay-grudev I think this might be related to our `pg_cron` installation... I've also noticed we don't pre-install `pg_cron` in the `postgres` database anywhere, which we definitely should be doing.

**Comment by Mohammed-Alhuraibi** [comment] 2024-10-09 14:06
@philippemnoel Yes, I tried the official CloudNativePG Helm chart as well before posting this issue. Unfortunately, it produced the same error.

**Comment by itay-grudev** [comment] 2024-10-09 18:28
Then this is consistent with my theory that the faulure is caused by the Pod Readiness check which fails once or twice while Postgres is booting up. This is perfectly normal behavior.

I'll close this. If you encounter any issues after initialization feel free to write us to re-open the issue.

**Closed by itay-grudev** 2024-10-09 18:28 UTC
Labels: enhancement, good first issue, priority-medium, question

**Comment by philippemnoel** [comment] 2024-10-09 18:56
Got it, thank you for sharing. If the issue is with CloudNativePG Helm chart, then you can open an issue there but this isn't relevant to ParadeDB

**Comment by Mohammed-Alhuraibi** [comment] 2024-10-10 07:21
Ok got it,  thank you so much for your help 👍🏼
